apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautobot
spec:
  project: understack
  sources:
    - repoURL: https://nautobot.github.io/helm-charts/
      chart: nautobot
      targetRevision: 2.1.0
      helm:
        releaseName: nautobot
        valueFiles:
          - $understack/components/nautobot/values.yaml
          - $secrets/helm-configs/${DEPLOY_NAME}/nautobot.yaml
        fileParameters:
          - name: nautobot.config
            # due to the following bug we must use a URL here
            # https://github.com/argoproj/argo-cd/issues/13220
            # but the goal would be to use a ref like
            # path: $understack/components/nautobot/nautobot_config.py
            path: https://raw.githubusercontent.com/rackerlabs/understack/${UC_REPO_REF}/components/nautobot/nautobot_config.py
    - repoURL: https://github.com/rackerlabs/understack.git
      path: components/nautobot/
      targetRevision: ${UC_REPO_REF}
      directory:
        include: dexauth-cm.yaml
      ref: understack
    - repoURL: ${UC_DEPLOY_GIT_URL}
      path: secrets/${DEPLOY_NAME}/
      targetRevision: ${UC_DEPLOY_REF}
      directory:
        include: 'secret-nautobot*.yaml'
        exclude: secret-nautobot-sso-dex.yaml
      ref: secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nautobot
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
